bezkoder:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://13.212.194.205
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: SignLanguage
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB